name = "Loraine"
uuid = "df0521af-66a0-42b3-822e-f30debbfe642"
authors = ["Michal Kocvara <kocvara@penopt.com>"]
version = "0.2.5"

[deps]
CSDP = "0a46da34-8e4b-519e-b418-48813639ff34"
ConjugateGradients = "f59de78d-195d-4e7b-a078-2e47da4c3ad6"
Dualization = "191a621a-6537-11e9-281d-650236a99e60"
FameSVD = "9ba2d756-9ce3-11e9-1a71-0ffcb019784d"
GenericLinearAlgebra = "14197337-ba66-59df-a3e3-ca00e7dcff7a"
JuMP = "4076af6c-e467-56ae-b986-b466b2749572"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MAT = "23992714-dd62-5051-b70f-ba57cb901cac"
MathOptInterface = "b8f27783-ece8-5eb3-8dc8-9495eed66fee"
MultiFloats = "bdf0d083-296b-4888-a5b6-7498122e68a5"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
TimerOutputs = "a759f4b9-e2f1-59dc-863e-4aeb61b1ea8f"

[compat]
ConjugateGradients = "0.1"
FameSVD = "0.1"
GenericLinearAlgebra = "0.3"
JuMP = "1"
MathOptInterface = "1"
MultiFloats = "2"
Revise = "3"
TimerOutputs = "0.5"
julia = "1"
