name = "Loraine"
uuid = "df0521af-66a0-42b3-822e-f30debbfe642"
authors = ["Michal Kocvara <kocvara@penopt.com>"]
version = "0.1.1"

[deps]
ConjugateGradients = "f59de78d-195d-4e7b-a078-2e47da4c3ad6"
FameSVD = "9ba2d756-9ce3-11e9-1a71-0ffcb019784d"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MathOptInterface = "b8f27783-ece8-5eb3-8dc8-9495eed66fee"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
TimerOutputs = "a759f4b9-e2f1-59dc-863e-4aeb61b1ea8f"

[compat]
ConjugateGradients = "0.1"
Dualization = "0.5"
MathOptInterface = "1"
Plots = "1"
Revise = "3.5"
TimerOutputs = "0.5"
julia = "1.6"
